version: '3.8'

volumes:
  postgres_data:
  staticfiles:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: lytkin/yamdb:v1.12.2020
    restart: always
    volumes:
      - staticfiles:/code/static/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.5
    volumes:
      - staticfiles:/static
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web